python MINE_util.py -s 1
python MINE_util.py -s 2
python MINE_util.py -s 3
python MINE_util.py -s 4
python MINE_util.py -s 5
python MINE_util.py -s 6
python MINE_util.py -s 7
python MINE_util.py -s 8
python MINE_util.py -s 9
python MINE_util.py -s 10
python MINE_util.py -s 11
python MINE_util.py -s 12
python MINE_util.py -s 13
python MINE_util.py -s 14
python MINE_util.py -s 15
python MINE_util.py -s 16
python MINE_util.py -s 17
python MINE_util.py -s 18
python MINE_util.py -s 19
python MINE_util.py -s 20
